"""
Comparison: Ensemble Voting vs Critic Model vs Actual Returns

This script analyzes the complete trading decision pipeline:
1. Load sp500_critic.csv (contains ensemble voting outputs + market data + technical indicators)
2. Extract test set using chronological split
3. Run critic model on voting outputs → timing decisions (immediate/wait_2_days)
4. Calculate actual returns at different horizons from forward_return columns
5. Compare:
   - What voting predicted (60/30/15/10 day horizons)
   - What critic recommended (immediate/wait 1/wait 2 days)
   - What actually happened (actual returns)

Input: sp500_critic.csv (generated by agent_main_loop.py)
Output: voting_vs_critic_comparison_now_or_2.csv with detailed analysis
"""

import numpy as np
import pandas as pd
from pathlib import Path
import warnings

warnings.filterwarnings('ignore', category=FutureWarning)
warnings.filterwarnings('ignore', category=DeprecationWarning)

try:
	import tensorflow as tf
	from tensorflow import keras
	print(f"TensorFlow {tf.__version__} loaded successfully")
except ImportError as e:
	print(f"Failed to import TensorFlow: {e}")
	tf = None
	keras = None

from scipy.stats import entropy
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler


def _require_tf():
	if tf is None:
		raise ImportError('TensorFlow is required. Install with `pip install tensorflow`.')


def load_critic_dataset(critic_csv_path=None):
	"""
	Load sp500_critic.csv which contains:
	- Original market features (Close, High, Low, Open, Volume)
	- Ensemble voting outputs (ensemble_prediction, ensemble_confidence, vote_entropy, etc.)
	- Forward return columns (forward_return_10/15/30/60 and _1/_2 variants)
	- Technical indicators (RSI, MACD, Bollinger Bands, ATR, etc.)
	- Strategy metrics
	
	Returns:
		DataFrame with all critic data
	"""
	repo_root = Path(__file__).resolve().parent
	if critic_csv_path is None:
		critic_csv_path = repo_root / 'data' / 'dataset' / 'sp500_critic.csv'
	
	critic_csv_path = Path(critic_csv_path)
	if not critic_csv_path.exists():
		raise FileNotFoundError(f"Critic CSV not found at: {critic_csv_path}")
	
	df = pd.read_csv(critic_csv_path)
	
	# Parse date
	if 'Date' in df.columns:
		df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
	
	print(f"Loaded critic dataset: {len(df)} rows, {len(df.columns)} columns")
	
	return df


def split_train_val_test_indices(n_samples, val_size=0.15, test_size=0.15):
	"""Split indices chronologically for time series."""
	test_idx = int(n_samples * (1 - test_size))
	val_idx = int(test_idx * (1 - val_size))
	
	train_indices = list(range(0, val_idx))
	val_indices = list(range(val_idx, test_idx))
	test_indices = list(range(test_idx, n_samples))
	
	return train_indices, val_indices, test_indices


def prepare_critic_features(df):
	"""
	Prepare feature matrix for critic model (matches agent_main_critic.py).
	
	Features include ONLY information available at decision time:
	1. Ensemble voting outputs (confidence, entropy, agreements)
	2. Market conditions (price, volume)
	3. Technical indicators (RSI, MACD, Bollinger Bands, ATR, momentum, etc.)
	4. Flags and reliability metrics
	
	EXCLUDED (future information):
	- forward_return_* (future returns)
	- strategy_class_* (derived from future returns)
	- strategy_confidence_* / strategy_margin_* (redundant)
	
	Total: ~36 features matching trained critic model
	"""
	feature_cols = []
	
	# 1. Ensemble voting outputs
	voting_cols = [
		'ensemble_prediction',
		'ensemble_confidence',
		'vote_entropy',
		'majority_percentage',
		'prediction_margin',
		'prediction_margin_normalized',
		'models_in_agreement',
		'agreement_percentage',
		'prob_class_0',
		'prob_class_1',
		'prob_class_2',
		'prob_class_3'
	]
	feature_cols.extend([c for c in voting_cols if c in df.columns])
	
	# 2. Market features
	market_cols = ['Close', 'High', 'Low', 'Open', 'Volume']
	feature_cols.extend([c for c in market_cols if c in df.columns])
	
	# 3. Technical indicators
	technical_cols = [
		'rsi_14', 'macd_line', 'macd_signal', 'macd_histogram',
		'bb_upper', 'bb_lower', 'bb_width', 'bb_position',
		'atr_14', 'momentum_10', 'sma_5', 'sma_20', 'ema_12',
		'price_position', 'volatility_20', 'volume_sma_20', 'volume_ratio'
	]
	feature_cols.extend([c for c in technical_cols if c in df.columns])
	
	# 4. Decision flags
	flag_cols = ['had_tie', 'low_confidence_flag']
	feature_cols.extend([c for c in flag_cols if c in df.columns])
	
	# Extract and prepare features
	X_df = df[feature_cols].copy()
	
	# Convert boolean to int
	for col in X_df.columns:
		if X_df[col].dtype == bool:
			X_df[col] = X_df[col].astype(int)
	
	# Handle missing values
	X_df = X_df.replace(["", " ", None], np.nan).fillna(0)
	for col in X_df.columns:
		X_df[col] = pd.to_numeric(X_df[col], errors='coerce').fillna(0)
	
	X = X_df.values.astype(np.float32)
	
	return X, feature_cols


def load_critic_model(models_dir: str | Path = None):
	"""Load trained critic model."""
	_require_tf()
	repo_root = Path(__file__).resolve().parent
	models_dir = Path(models_dir) if models_dir else (repo_root / 'models')
	critic_path = models_dir / 'critic_best.keras'
	
	if not critic_path.exists():
		print(f"Warning: critic model not found at {critic_path}")
		return None
	
	try:
		critic = keras.models.load_model(critic_path)
		print(f"Loaded critic model from {critic_path}")
		return critic
	except Exception as e:
		print(f"Error loading critic model: {e}")
		return None


def run_critic_inference(critic_model, X_test):
	"""
	Run critic inference to get timing decisions.
	
	Returns:
		Dict with timing decisions and probabilities
	"""
	if critic_model is None:
		print("Critic model not available")
		return None
	
	try:
		timing_probs = critic_model.predict(X_test, verbose=0)  # (n_samples, 3)
		timing_preds = np.argmax(timing_probs, axis=1)
		timing_confs = np.max(timing_probs, axis=1)
		
		# Timing classes: 0=immediate, 1=wait_2_days
		timing_names = {0: 'immediate', 1: 'wait_2_days'}
		timing_pred_names = np.array([timing_names[t] for t in timing_preds])
		
		return {
			'timing_predictions': timing_preds,
			'timing_confidences': timing_confs,
			'timing_probabilities': timing_probs,
			'timing_names': timing_pred_names,
		}
	except Exception as e:
		print(f"Error running critic inference: {e}")
		return None


def extract_actual_returns_from_critic_csv(df_test):
	"""
	Extract actual returns from forward_return columns in sp500_critic.csv.
	
	The critic CSV already has forward_return_10, forward_return_15, forward_return_30, forward_return_60
	which represent actual returns at those horizons.
	
	Returns:
		Dict with arrays of actual returns for each horizon
	"""
	returns = {}
	
	for period in [10, 15, 30, 60]:
		col_name = f'forward_return_{period}'
		if col_name in df_test.columns:
			returns[period] = df_test[col_name].values.astype(np.float32)
		else:
			print(f"Warning: Column {col_name} not found in critic CSV")
			returns[period] = np.full(len(df_test), np.nan, dtype=np.float32)
	
	return returns


def generate_comparison_report(df_test, timing_results, actual_returns):
	"""
	Generate detailed comparison report between voting, critic, and actual returns.
	
	Args:
		df_test: Test set DataFrame from sp500_critic.csv
		timing_results: Dict with critic timing predictions
		actual_returns: Dict with actual returns {10: array, 15: array, 30: array, 60: array}
	
	Returns:
		DataFrame with comparison results
	"""
	period_names = {0: '60-day', 1: '30-day', 2: '15-day', 3: '10-day'}
	period_to_days = {0: 60, 1: 30, 2: 15, 3: 10}
	timing_names = {0: 'immediate', 1: 'wait_2_days'}
	
	n_samples = len(df_test)
	
	# Extract ensemble voting outputs
	ensemble_preds = df_test['ensemble_prediction'].values
	ensemble_confs = df_test['ensemble_confidence'].values
	
	# Map voting prediction to actual return at that horizon
	predicted_returns = np.zeros(n_samples, dtype=np.float32)
	predicted_horizons = []
	
	for i in range(n_samples):
		pred_class = int(ensemble_preds[i])
		horizon_days = period_to_days.get(pred_class, 30)
		predicted_horizons.append(period_names[pred_class])
		predicted_returns[i] = actual_returns[horizon_days][i]
	
	# Create comparison dataframe
	comparison_df = pd.DataFrame({
		'date': df_test['Date'].values if 'Date' in df_test.columns else range(n_samples),
		'voting_prediction': predicted_horizons,
		'voting_confidence': ensemble_confs,
		'voting_class': ensemble_preds,
		'prob_60day': df_test['prob_class_0'].values if 'prob_class_0' in df_test.columns else np.nan,
		'prob_30day': df_test['prob_class_1'].values if 'prob_class_1' in df_test.columns else np.nan,
		'prob_15day': df_test['prob_class_2'].values if 'prob_class_2' in df_test.columns else np.nan,
		'prob_10day': df_test['prob_class_3'].values if 'prob_class_3' in df_test.columns else np.nan,
		'actual_return_60day': actual_returns[60],
		'actual_return_30day': actual_returns[30],
		'actual_return_15day': actual_returns[15],
		'actual_return_10day': actual_returns[10],
		'predicted_return': predicted_returns,
	})
	
	# Add critic results if available
	if timing_results:
		timing_preds = timing_results['timing_predictions']
		timing_confs = timing_results['timing_confidences']
		
		comparison_df['timing_decision'] = [timing_names[t] for t in timing_preds]
		comparison_df['timing_confidence'] = timing_confs
		comparison_df['timing_class'] = timing_preds
	
	return comparison_df


def generate_summary_statistics(comparison_df, timing_results):
	"""
	Generate summary statistics for the comparison report.
	
	Returns:
		Dict with summary statistics
	"""
	summary = {}
	
	# Period mapping
	period_names = {0: '60-day', 1: '30-day', 2: '15-day', 3: '10-day'}
	period_to_days = {0: 60, 1: 30, 2: 15, 3: 10}
	return_col_map = {60: 'actual_return_60day', 30: 'actual_return_30day', 15: 'actual_return_15day', 10: 'actual_return_10day'}
	
	# ====================================================================
	# CUMULATIVE RETURNS BY PERIOD (Actual vs Predicted)
	# ====================================================================
	cumulative_stats = {}
	
	for period_days, period_label in [(10, '10-day'), (15, '15-day'), (30, '30-day'), (60, '60-day')]:
		# Actual returns for this period
		actual_col = return_col_map[period_days]
		actual_rets = comparison_df[actual_col].values
		actual_rets = actual_rets[~np.isnan(actual_rets)]
		actual_sum = np.sum(actual_rets)
		
		# Predicted returns: sum returns where this period was predicted
		period_key = [k for k, v in period_to_days.items() if v == period_days][0]
		mask = comparison_df['voting_class'] == period_key
		predicted_rets = comparison_df.loc[mask, actual_col].values
		predicted_rets = predicted_rets[~np.isnan(predicted_rets)]
		predicted_sum = np.sum(predicted_rets)
		
		cumulative_stats[period_label] = {
			'actual_sum': float(actual_sum),
			'predicted_sum': float(predicted_sum),
			'actual_count': int(len(actual_rets)),
			'predicted_count': int(len(predicted_rets)),
			'predicted_vs_max': 0.0  # Will be calculated after
		}
	
	# Calculate max actual sum across all periods
	max_actual = max([v['actual_sum'] for v in cumulative_stats.values()]) if cumulative_stats else 1.0
	if max_actual == 0:
		max_actual = 1.0  # Avoid division by zero
	
	# Calculate ratios (predicted / max_actual)
	for period_label in cumulative_stats:
		cumulative_stats[period_label]['predicted_vs_max'] = cumulative_stats[period_label]['predicted_sum'] / max_actual
	
	summary['cumulative_returns'] = cumulative_stats
	
	# ====================================================================
	# VOTING PREDICTIONS ANALYSIS
	# ====================================================================
	voting_stats = {}
	
	for voting_class, period_name in period_names.items():
		mask = comparison_df['voting_class'] == voting_class
		if mask.sum() > 0:
			returns = comparison_df.loc[mask, 'predicted_return'].values
			valid_rets = returns[~np.isnan(returns)]
			
			if len(valid_rets) > 0:
				voting_stats[period_name] = {
					'samples': int(mask.sum()),
					'mean_return': float(np.mean(valid_rets)),
					'median_return': float(np.median(valid_rets)),
					'std_return': float(np.std(valid_rets)),
					'win_rate': float(np.sum(valid_rets > 0) / len(valid_rets) * 100),
					'best': float(np.max(valid_rets)),
					'worst': float(np.min(valid_rets))
				}
	
	summary['voting_stats'] = voting_stats
	
	# Critic timing analysis
	if timing_results and 'timing_class' in comparison_df.columns:
		timing_names = {0: 'immediate', 1: 'wait_2_days'}
		timing_stats = {}
		
		for timing_id, timing_name in timing_names.items():
			mask = comparison_df['timing_class'] == timing_id
			if mask.sum() > 0:
				returns = comparison_df.loc[mask, 'predicted_return'].values
				valid_rets = returns[~np.isnan(returns)]
				
				if len(valid_rets) > 0:
					timing_stats[timing_name] = {
						'samples': int(mask.sum()),
						'mean_return': float(np.mean(valid_rets)),
						'median_return': float(np.median(valid_rets)),
						'std_return': float(np.std(valid_rets)),
						'win_rate': float(np.sum(valid_rets > 0) / len(valid_rets) * 100),
						'best': float(np.max(valid_rets)),
						'worst': float(np.min(valid_rets))
					}
		
		summary['timing_stats'] = timing_stats
		
		# Correlation between critic confidence and returns
		valid_mask = ~np.isnan(comparison_df['predicted_return'])
		if valid_mask.sum() > 1:
			corr = np.corrcoef(
				comparison_df.loc[valid_mask, 'timing_confidence'],
				comparison_df.loc[valid_mask, 'predicted_return']
			)[0, 1]
			summary['confidence_return_correlation'] = float(corr)
	
	# Best horizon analysis
	horizon_stats = {}
	for col, horizon_name in [('actual_return_60day', '60-day'), 
	                           ('actual_return_30day', '30-day'),
	                           ('actual_return_15day', '15-day'),
	                           ('actual_return_10day', '10-day')]:
		if col in comparison_df.columns:
			vals = comparison_df[col].values
			valid = vals[~np.isnan(vals)]
			if len(valid) > 0:
				horizon_stats[horizon_name] = {
					'mean': float(np.mean(valid)),
					'win_rate': float(np.sum(valid > 0) / len(valid) * 100)
				}
	
	summary['horizon_stats'] = horizon_stats
	
	return summary


def save_comparison_report(comparison_df, timing_results, summary_stats, output_path='results/voting_critic_comparison_report_now_or_2.txt'):
	"""
	Save detailed comparison report to text file.
	"""
	output_path = Path(output_path)
	output_path.parent.mkdir(parents=True, exist_ok=True)
	
	with open(output_path, 'w') as f:
		f.write("="*80 + "\n")
		f.write("ENSEMBLE VOTING vs CRITIC vs ACTUAL RETURNS - COMPARISON REPORT\n")
		f.write("="*80 + "\n\n")
		
		# Dataset info
		f.write("DATASET INFORMATION\n")
		f.write("-" * 80 + "\n")
		f.write(f"Total test samples: {len(comparison_df)}\n")
		if 'date' in comparison_df.columns:
			f.write(f"Test period: {comparison_df['date'].iloc[0]} to {comparison_df['date'].iloc[-1]}\n")
		f.write("\n")
		
		# ====================================================================
		# CUMULATIVE RETURNS BY PERIOD
		# ====================================================================
		f.write("="*80 + "\n")
		f.write("CUMULATIVE RETURNS BY PERIOD (Actual vs Predicted)\n")
		f.write("="*80 + "\n\n")
		
		cumulative_stats = summary_stats.get('cumulative_returns', {})
		
		if cumulative_stats:
			f.write("Period      | Actual Sum  | Predicted Sum | Pred/Max Ratio | Pred Count | Total Count\n")
			f.write("-" * 115 + "\n")
			for period_label in ['10-day', '15-day', '30-day', '60-day']:
				if period_label in cumulative_stats:
					stats = cumulative_stats[period_label]
					f.write(f"{period_label:11s} | {stats['actual_sum']:+11.6f} | {stats['predicted_sum']:+13.6f} | {stats['predicted_vs_max']:14.4f} | {stats['predicted_count']:10d} | {stats['actual_count']:11d}\n")
			f.write("\n")
		
		# ====================================================================
		# VOTING PREDICTIONS vs ACTUAL RETURNS
		# ====================================================================
		f.write("="*80 + "\n")
		f.write("VOTING PREDICTIONS vs ACTUAL RETURNS\n")
		f.write("="*80 + "\n\n")
		
		voting_stats = summary_stats.get('voting_stats', {})
		
		for period_name in ['60-day', '30-day', '15-day', '10-day']:
			if period_name in voting_stats:
				stats = voting_stats[period_name]
				f.write(f"{period_name} Horizon:\n")
				f.write(f"  Samples: {stats['samples']}\n")
				f.write(f"  Mean return: {stats['mean_return']:+.4f} ({stats['mean_return']*100:+.2f}%)\n")
				f.write(f"  Median return: {stats['median_return']:+.4f} ({stats['median_return']*100:+.2f}%)\n")
				f.write(f"  Std dev: {stats['std_return']:.4f}\n")
				f.write(f"  Win rate: {stats['win_rate']:.1f}%\n")
				f.write(f"  Best: {stats['best']:+.4f} | Worst: {stats['worst']:+.4f}\n\n")
		
		# ====================================================================
		# CRITIC TIMING ANALYSIS
		# ====================================================================
		if 'timing_stats' in summary_stats:
			f.write("="*80 + "\n")
			f.write("CRITIC TIMING ANALYSIS\n")
			f.write("="*80 + "\n\n")
			
			timing_stats = summary_stats['timing_stats']
			
			for timing_name in ['immediate', 'wait_2_days']:
				if timing_name in timing_stats:
					stats = timing_stats[timing_name]
					f.write(f"Timing: {timing_name}\n")
					f.write(f"  Samples: {stats['samples']}\n")
					f.write(f"  Mean return: {stats['mean_return']:+.4f} ({stats['mean_return']*100:+.2f}%)\n")
					f.write(f"  Median return: {stats['median_return']:+.4f} ({stats['median_return']*100:+.2f}%)\n")
					f.write(f"  Std dev: {stats['std_return']:.4f}\n")
					f.write(f"  Win rate: {stats['win_rate']:.1f}%\n")
					f.write(f"  Best: {stats['best']:+.4f} | Worst: {stats['worst']:+.4f}\n\n")
			
			if 'confidence_return_correlation' in summary_stats:
				f.write(f"Correlation between critic confidence and returns: {summary_stats['confidence_return_correlation']:.4f}\n\n")
		
		# ====================================================================
		# BEST HORIZON ANALYSIS
		# ====================================================================
		f.write("="*80 + "\n")
		f.write("WHICH HORIZON WAS ACTUALLY BEST?\n")
		f.write("="*80 + "\n\n")
		
		horizon_stats = summary_stats.get('horizon_stats', {})
		
		for horizon_name in ['60-day', '30-day', '15-day', '10-day']:
			if horizon_name in horizon_stats:
				stats = horizon_stats[horizon_name]
				f.write(f"{horizon_name}: mean={stats['mean']:+.4f} ({stats['mean']*100:+.2f}%), ")
				f.write(f"win rate={stats['win_rate']:.1f}%\n")
		
		# ====================================================================
		# KEY INSIGHTS
		# ====================================================================
		f.write("\n" + "="*80 + "\n")
		f.write("KEY INSIGHTS\n")
		f.write("="*80 + "\n\n")
		
		# Best performing voting horizon
		if voting_stats:
			best_voting = max(voting_stats.items(), key=lambda x: x[1]['mean_return'])
			f.write(f"Best voting horizon by mean return: {best_voting[0]} ({best_voting[1]['mean_return']*100:+.2f}%)\n")
		
		# Best performing timing
		if 'timing_stats' in summary_stats:
			timing_stats = summary_stats['timing_stats']
			if timing_stats:
				best_timing = max(timing_stats.items(), key=lambda x: x[1]['mean_return'])
				f.write(f"Best critic timing by mean return: {best_timing[0]} ({best_timing[1]['mean_return']*100:+.2f}%)\n")
		
		# Best actual horizon
		if horizon_stats:
			best_horizon = max(horizon_stats.items(), key=lambda x: x[1]['mean'])
			f.write(f"Best actual horizon overall: {best_horizon[0]} ({best_horizon[1]['mean']*100:+.2f}%)\n")
		
		f.write("\n" + "="*80 + "\n")
		f.write("END OF REPORT\n")
		f.write("="*80 + "\n")
	
	print(f"  ✓ Saved detailed report to {output_path}")


def print_comparison_summary(comparison_df, timing_results):
	"""
	Print detailed summary of comparison results to console.
	"""
	print("="*80)
	print("COMPARISON SUMMARY")
	print("="*80 + "\n")
	
	summary_stats = generate_summary_statistics(comparison_df, timing_results)
	
	# ========================================================================
	# CUMULATIVE RETURNS BY PERIOD
	# ========================================================================
	print("CUMULATIVE RETURNS BY PERIOD (Actual vs Predicted):")
	print("-" * 80)
	
	cumulative_stats = summary_stats.get('cumulative_returns', {})
	
	if cumulative_stats:
		print(f"{'Period':11s} | {'Actual Sum':>11s} | {'Predicted Sum':>13s} | {'Pred/Max':>10s}")
		print("-" * 60)
		for period_label in ['10-day', '15-day', '30-day', '60-day']:
			if period_label in cumulative_stats:
				stats = cumulative_stats[period_label]
				print(f"{period_label:11s} | {stats['actual_sum']:+11.6f} | {stats['predicted_sum']:+13.6f} | {stats['predicted_vs_max']:10.4f}")
		print()
	
	# ========================================================================
	# VOTING PREDICTIONS vs ACTUAL RETURNS
	# ========================================================================
	print("VOTING PREDICTIONS vs ACTUAL RETURNS:")
	print("-" * 80)
	
	voting_stats = summary_stats.get('voting_stats', {})
	
	for period_name in ['60-day', '30-day', '15-day', '10-day']:
		if period_name in voting_stats:
			stats = voting_stats[period_name]
			print(f"\n{period_name} Horizon:")
			print(f"  Samples: {stats['samples']}")
			print(f"  Mean return: {stats['mean_return']:+.4f} ({stats['mean_return']*100:+.2f}%)")
			print(f"  Median return: {stats['median_return']:+.4f} ({stats['median_return']*100:+.2f}%)")
			print(f"  Std dev: {stats['std_return']:.4f}")
			print(f"  Win rate: {stats['win_rate']:.1f}%")
			print(f"  Best: {stats['best']:+.4f} | Worst: {stats['worst']:+.4f}")
	
	# ========================================================================
	# CRITIC TIMING ANALYSIS
	# ========================================================================
	if 'timing_stats' in summary_stats:
		print("\n" + "="*80)
		print("CRITIC TIMING ANALYSIS:")
		print("-" * 80)
		
		timing_stats = summary_stats['timing_stats']
		
		for timing_name in ['immediate', 'wait_2_days']:
			if timing_name in timing_stats:
				stats = timing_stats[timing_name]
				print(f"\nTiming: {timing_name}")
				print(f"  Samples: {stats['samples']}")
				print(f"  Mean return: {stats['mean_return']:+.4f} ({stats['mean_return']*100:+.2f}%)")
				print(f"  Median return: {stats['median_return']:+.4f} ({stats['median_return']*100:+.2f}%)")
				print(f"  Std dev: {stats['std_return']:.4f}")
				print(f"  Win rate: {stats['win_rate']:.1f}%")
				print(f"  Best: {stats['best']:+.4f} | Worst: {stats['worst']:+.4f}")
		
		if 'confidence_return_correlation' in summary_stats:
			print(f"\nCorrelation between critic confidence and returns: {summary_stats['confidence_return_correlation']:.4f}")
	
	# ========================================================================
	# BEST HORIZON ANALYSIS
	# ========================================================================
	print("\n" + "="*80)
	print("WHICH HORIZON WAS ACTUALLY BEST?")
	print("-" * 80)
	
	horizon_stats = summary_stats.get('horizon_stats', {})
	
	for horizon_name in ['60-day', '30-day', '15-day', '10-day']:
		if horizon_name in horizon_stats:
			stats = horizon_stats[horizon_name]
			print(f"{horizon_name}: mean={stats['mean']:+.4f}, win rate={stats['win_rate']:.1f}%")
	
	return summary_stats


def analyze_timing_by_period(comparison_df):
	"""
	Analyze critic timing decisions broken down by period returns.
	
	For each timing decision, calculate returns across all periods.
	"""
	timing_analysis = {}
	timing_names = {0: 'immediate', 1: 'wait_2_days'}
	period_cols = ['actual_return_10day', 'actual_return_15day', 'actual_return_30day', 'actual_return_60day']
	period_labels = ['10-day', '15-day', '30-day', '60-day']
	
	if 'timing_class' not in comparison_df.columns:
		return timing_analysis
	
	for timing_class in [0, 1]:
		timing_name = timing_names[timing_class]
		mask = (comparison_df['timing_class'] == timing_class)
		
		if mask.sum() == 0:
			continue
		
		timing_data = comparison_df[mask]
		confidences = timing_data['timing_confidence'].values
		
		period_stats = {}
		for col, label in zip(period_cols, period_labels):
			if col in timing_data.columns:
				rets = timing_data[col].values.astype(float)
				rets = rets[~np.isnan(rets)]
				
				if len(rets) > 0:
					period_stats[label] = {
						'count': len(rets),
						'sum': float(np.sum(rets)),
						'mean': float(np.mean(rets)),
						'median': float(np.median(rets)),
						'std': float(np.std(rets)),
						'win_rate': float(np.sum(rets > 0) / len(rets) * 100),
						'best': float(np.max(rets)),
						'worst': float(np.min(rets))
					}
		
		timing_analysis[timing_name] = {
			'count': int(mask.sum()),
			'confidence_mean': float(np.mean(confidences)),
			'confidence_std': float(np.std(confidences)),
			'period_stats': period_stats
		}
	
	return timing_analysis


def print_timing_by_period(timing_analysis):
	"""
	Print timing analysis by period to console.
	"""
	print("\n" + "="*100)
	print("CRITIC TIMING ANALYSIS: Returns by Timing Decision")
	print("="*100)
	
	for timing_name, stats in timing_analysis.items():
		print(f"\nTiming: {timing_name}")
		print("-" * 100)
		print(f"  Samples: {stats['count']}")
		print(f"  Mean confidence: {stats['confidence_mean']:.4f} (±{stats['confidence_std']:.4f})\n")
		
		period_stats = stats.get('period_stats', {})
		if period_stats:
			print(f"  {'Period':>8s} | {'Count':>6s} | {'Sum':>12s} | {'Mean':>10s} | {'Median':>10s} | {'Win%':>7s} | {'Best':>10s} | {'Worst':>10s}")
			print(f"  {'-'*100}")
			
			for period in ['10-day', '15-day', '30-day', '60-day']:
				if period in period_stats:
					ps = period_stats[period]
					print(f"  {period:>8s} | {ps['count']:6d} | {ps['sum']:+12.6f} | {ps['mean']:+10.6f} | {ps['median']:+10.6f} | {ps['win_rate']:7.1f} | {ps['best']:+10.6f} | {ps['worst']:+10.6f}")


def save_timing_by_period(timing_analysis, output_path='results/timing_by_period_now_or_2.txt'):
	"""
	Save timing analysis by period to text file.
	"""
	output_path = Path(output_path)
	output_path.parent.mkdir(parents=True, exist_ok=True)
	
	with open(output_path, 'w') as f:
		f.write("="*100 + "\n")
		f.write("CRITIC TIMING ANALYSIS: Returns by Timing Decision\n")
		f.write("="*100 + "\n\n")
		
		for timing_name, stats in timing_analysis.items():
			f.write(f"Timing: {timing_name}\n")
			f.write("-" * 100 + "\n")
			f.write(f"  Samples: {stats['count']}\n")
			f.write(f"  Mean confidence: {stats['confidence_mean']:.4f} (±{stats['confidence_std']:.4f})\n\n")
			
			period_stats = stats.get('period_stats', {})
			if period_stats:
				f.write(f"  {'Period':>8s} | {'Count':>6s} | {'Sum':>12s} | {'Mean':>10s} | {'Median':>10s} | {'Win%':>7s} | {'Best':>10s} | {'Worst':>10s}\n")
				f.write(f"  {'-'*100}\n")
				
				for period in ['10-day', '15-day', '30-day', '60-day']:
					if period in period_stats:
						ps = period_stats[period]
						f.write(f"  {period:>8s} | {ps['count']:6d} | {ps['sum']:+12.6f} | {ps['mean']:+10.6f} | {ps['median']:+10.6f} | {ps['win_rate']:7.1f} | {ps['best']:+10.6f} | {ps['worst']:+10.6f}\n")
			f.write("\n")
	
	print(f"  ✓ Saved timing analysis to {output_path}")


def main():
	"""
	Main comparison pipeline:
	1. Load sp500_critic.csv (has ensemble voting + technical indicators + forward returns)
	2. Extract test set
	3. Prepare critic features and run critic model
	4. Compare voting predictions vs critic timing vs actual returns
	5. Generate detailed analysis report
	"""
	print("="*80)
	print("ENSEMBLE VOTING vs CRITIC vs ACTUAL RETURNS COMPARISON")
	print("="*80 + "\n")
	
	# ========================================================================
	# STEP 1: Load Critic Dataset
	# ========================================================================
	print("STEP 1: Loading critic dataset (sp500_critic.csv)...")
	df_full = load_critic_dataset()
	print(f"  Total samples: {len(df_full)}")
	
	# Check for required columns
	required_cols = ['ensemble_prediction', 'ensemble_confidence', 'Close']
	missing = [c for c in required_cols if c not in df_full.columns]
	if missing:
		print(f"ERROR: Missing required columns: {missing}")
		print("Please run agent_main_loop.py first to generate sp500_critic.csv")
		return
	
	print()
	
	# ========================================================================
	# STEP 2: Split Data into Train/Val/Test
	# ========================================================================
	print("STEP 2: Splitting data chronologically...")
	train_idx, val_idx, test_idx = split_train_val_test_indices(len(df_full))
	
	df_test = df_full.iloc[test_idx].reset_index(drop=True)
	
	print(f"  Train: {len(train_idx)} samples")
	print(f"  Val: {len(val_idx)} samples")
	print(f"  Test: {len(test_idx)} samples")
	
	if 'Date' in df_test.columns:
		print(f"  Test period: {df_test['Date'].iloc[0]} to {df_test['Date'].iloc[-1]}")
	print()
	
	# ========================================================================
	# STEP 3: Prepare Features and Load Critic Model
	# ========================================================================
	print("STEP 3: Preparing critic features and loading model...")
	X_full, feature_cols = prepare_critic_features(df_full)
	print(f"  Feature matrix shape: {X_full.shape}")
	print(f"  Number of features: {len(feature_cols)}")
	
	# Extract test set features
	X_test = X_full[test_idx]
	
	# Normalize (using StandardScaler like in agent_main_critic.py)
	print("  Normalizing features with StandardScaler...")
	scaler = StandardScaler()
	# Fit on train, transform test
	X_train = X_full[train_idx]
	scaler.fit(X_train)
	X_test_scaled = scaler.transform(X_test)
	
	# Load critic model
	critic_model = load_critic_model()
	print()
	
	# ========================================================================
	# STEP 4: Run Critic Inference
	# ========================================================================
	if critic_model is None:
		print("STEP 4: Skipping critic inference (model not available)\n")
		timing_results = None
	else:
		print("STEP 4: Running critic inference...")
		timing_results = run_critic_inference(critic_model, X_test_scaled)
		
		if timing_results:
			timing_preds = timing_results['timing_predictions']
			timing_confs = timing_results['timing_confidences']
			timing_names_map = {0: 'immediate', 1: 'wait_2_days'}
			timing_counts = {t: np.sum(timing_preds == i) for i, t in timing_names_map.items()}
			
			print(f"  Critic results:")
			print(f"    Mean confidence: {np.mean(timing_confs):.4f}")
			for timing, count in timing_counts.items():
				print(f"    {timing}: {count} samples ({100*count/len(X_test):.1f}%)")
		print()
	
	# ========================================================================
	# STEP 5: Extract Actual Returns from Critic CSV
	# ========================================================================
	print("STEP 5: Extracting actual returns from forward_return columns...")
	actual_returns = extract_actual_returns_from_critic_csv(df_test)
	
	for period in [60, 30, 15, 10]:
		rets = actual_returns[period]
		valid = rets[~np.isnan(rets)]
		if len(valid) > 0:
			print(f"  {period}-day: mean={np.mean(valid):+.4f}, std={np.std(valid):.4f}, samples={len(valid)}")
	print()
	
	# ========================================================================
	# STEP 6: Generate Comparison Report
	# ========================================================================
	print("STEP 6: Generating comparison report...")
	comparison_df = generate_comparison_report(df_test, timing_results, actual_returns)
	
	# Save results
	results_dir = Path(__file__).resolve().parent / 'results'
	results_dir.mkdir(parents=True, exist_ok=True)
	
	# Save CSV
	comparison_csv = results_dir / 'voting_vs_critic_comparison_now_or_2.csv'
	comparison_df.to_csv(comparison_csv, index=False)
	print(f"  ✓ Saved comparison data to {comparison_csv}")
	
	# ========================================================================
	# STEP 7: Generate and Print Summary Statistics
	# ========================================================================
	print("\nSTEP 7: Generating summary statistics...")
	summary_stats = print_comparison_summary(comparison_df, timing_results)
	
	# Save detailed text report
	print("\nSTEP 8: Saving detailed report...")
	comparison_txt = results_dir / 'voting_vs_critic_comparison_report_now_or_2.txt'
	save_comparison_report(comparison_df, timing_results, summary_stats, output_path=comparison_txt)
	
	# Analyze and save timing breakdown by period
	if timing_results:
		print("\nSTEP 9: Analyzing timing decisions by period...")
		timing_analysis = analyze_timing_by_period(comparison_df)
		if timing_analysis:
			print_timing_by_period(timing_analysis)
			timing_txt = results_dir / 'timing_by_period_now_or_2.txt'
			save_timing_by_period(timing_analysis, output_path=timing_txt)
	
	print("\n" + "="*80)
	print("FILES SAVED:")
	print("="*80)
	print(f"  CSV (detailed data):  {comparison_csv}")
	print(f"  TXT (summary report): {comparison_txt}")
	if timing_results:
		print(f"  TXT (timing analysis): {timing_txt}")
	print("="*80)


if __name__ == '__main__':
	main()
